/********************************************************************
* ROOT_dicts.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ROOT_dicts.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableROOT_dicts();
extern void G__cpp_setup_inheritanceROOT_dicts();
extern void G__cpp_setup_typetableROOT_dicts();
extern void G__cpp_setup_memvarROOT_dicts();
extern void G__cpp_setup_globalROOT_dicts();
extern void G__cpp_setup_memfuncROOT_dicts();
extern void G__cpp_setup_funcROOT_dicts();
extern void G__set_cpp_environmentROOT_dicts();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TreeParticles.hpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ROOT_dictsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ROOT_dictsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ROOT_dictsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ROOT_dictsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ROOT_dictsLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ROOT_dictsLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ROOT_dictsLN_TLorentzVector;
extern G__linked_taginfo G__ROOT_dictsLN_tree;
extern G__linked_taginfo G__ROOT_dictsLN_treecLcLParticle;
extern G__linked_taginfo G__ROOT_dictsLN_treecLcLPhoton;
extern G__linked_taginfo G__ROOT_dictsLN_treecLcLJet;
extern G__linked_taginfo G__ROOT_dictsLN_vectorlEtreecLcLPhotoncOallocatorlEtreecLcLPhotongRsPgR;
extern G__linked_taginfo G__ROOT_dictsLN_vectorlEtreecLcLPhotoncOallocatorlEtreecLcLPhotongRsPgRcLcLiterator;
extern G__linked_taginfo G__ROOT_dictsLN_reverse_iteratorlEvectorlEtreecLcLPhotoncOallocatorlEtreecLcLPhotongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ROOT_dictsLN_vectorlEtreecLcLParticlecOallocatorlEtreecLcLParticlegRsPgR;
extern G__linked_taginfo G__ROOT_dictsLN_vectorlEtreecLcLParticlecOallocatorlEtreecLcLParticlegRsPgRcLcLiterator;
extern G__linked_taginfo G__ROOT_dictsLN_reverse_iteratorlEvectorlEtreecLcLParticlecOallocatorlEtreecLcLParticlegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ROOT_dictsLN_vectorlEtreecLcLJetcOallocatorlEtreecLcLJetgRsPgR;
extern G__linked_taginfo G__ROOT_dictsLN_vectorlEtreecLcLJetcOallocatorlEtreecLcLJetgRsPgRcLcLiterator;
extern G__linked_taginfo G__ROOT_dictsLN_reverse_iteratorlEvectorlEtreecLcLJetcOallocatorlEtreecLcLJetgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ROOT_dictsLN_vectorlETVector3cOallocatorlETVector3gRsPgR;
extern G__linked_taginfo G__ROOT_dictsLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ROOT_dictsLN_vectorlEvectorlETVector3cOallocatorlETVector3gRsPgRcOallocatorlEvectorlETVector3cOallocatorlETVector3gRsPgRsPgRsPgR;
extern G__linked_taginfo G__ROOT_dictsLN_vectorlEvectorlETVector3cOallocatorlETVector3gRsPgRcOallocatorlEvectorlETVector3cOallocatorlETVector3gRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__ROOT_dictsLN_reverse_iteratorlEvectorlEvectorlETVector3cOallocatorlETVector3gRsPgRcOallocatorlEvectorlETVector3cOallocatorlETVector3gRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<tree::Photon,allocator<tree::Photon> > G__vectorlEtreecLcLPhotoncOallocatorlEtreecLcLPhotongRsPgR;
typedef vector<tree::Particle,allocator<tree::Particle> > G__vectorlEtreecLcLParticlecOallocatorlEtreecLcLParticlegRsPgR;
typedef vector<tree::Jet,allocator<tree::Jet> > G__vectorlEtreecLcLJetcOallocatorlEtreecLcLJetgRsPgR;
typedef vector<vector<TVector3,allocator<TVector3> >,allocator<vector<TVector3,allocator<TVector3> > > > G__vectorlEvectorlETVector3cOallocatorlETVector3gRsPgRcOallocatorlEvectorlETVector3cOallocatorlETVector3gRsPgRsPgRsPgR;
